//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polokus.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polokus.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0fzn1yw&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_01mfi35&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoundaryEventMessage {
            get {
                return ResourceManager.GetString("BoundaryEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0fzn1yw&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_01mfi35&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoundaryEventTimer1 {
            get {
                return ResourceManager.GetString("BoundaryEventTimer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0wf64wc&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_11mzzxa&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoundaryEventTimer2 {
            get {
                return ResourceManager.GetString("BoundaryEventTimer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn2:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn2=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;sample-diagram&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; xsi:schemaLocation=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd&quot;&gt;
        ///  &lt;bpmn2:process id=&quot;Process_1&quot; isExecutable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DelayTask {
            get {
                return ResourceManager.GetString("DelayTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn2:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn2=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;sample-diagram&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; xsi:schemaLocation=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd&quot;&gt;
        ///  &lt;bpmn2:process id=&quot;Process_1&quot; isExecutable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExceptionBoundaryEvent {
            get {
                return ResourceManager.GetString("ExceptionBoundaryEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1jzw7sx&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1gat3xk&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exclusive1 {
            get {
                return ResourceManager.GetString("Exclusive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_11rphux&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_0ztjch0&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exclusive2 {
            get {
                return ResourceManager.GetString("Exclusive2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn2:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn2=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;sample-diagram&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; xsi:schemaLocation=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd&quot;&gt;
        ///  &lt;bpmn2:process id=&quot;Process_1&quot; isExecutable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileSegregation {
            get {
                return ResourceManager.GetString("FileSegregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn2:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn2=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;sample-diagram&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.4.1&quot; xsi:schemaLocation=&quot;http://www.omg.org/spec/BPMN/20100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GradingStudent {
            get {
                return ResourceManager.GetString("GradingStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1vib7aw&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1gdeqgm&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inclusive1 {
            get {
                return ResourceManager.GetString("Inclusive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_15pibiv&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.3.0&quot;&gt;
        ///  &lt;bpmn:collaboration id=&quot;Collaboration_17e7kfs&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBetweenProcesses1 {
            get {
                return ResourceManager.GetString("MsgBetweenProcesses1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0vpgi5m&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.3.0&quot;&gt;
        ///  &lt;bpmn:collaboration id=&quot;Collaboration_0ovyeyy&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBetweenProcesses2 {
            get {
                return ResourceManager.GetString("MsgBetweenProcesses2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0vpgi5m&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.3.0&quot;&gt;
        ///  &lt;bpmn:collaboration id=&quot;Collaboration_0ovyeyy&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBetweenProcesses3 {
            get {
                return ResourceManager.GetString("MsgBetweenProcesses3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0xqstfg&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:collaboration id=&quot;Collaboration_0uk8350&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBetweenProcesses4 {
            get {
                return ResourceManager.GetString("MsgBetweenProcesses4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0ebpa1l&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_0vsqp9p&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgStart {
            get {
                return ResourceManager.GetString("MsgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1jzw7sx&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;9.3.2&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1gat3xk&quot; isExecutable=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Parallel1 {
            get {
                return ResourceManager.GetString("Parallel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0idzrvk&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_094p06o&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Parallel2 {
            get {
                return ResourceManager.GetString("Parallel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0437in3&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_150dmg2&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptTask1 {
            get {
                return ResourceManager.GetString("ScriptTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1kcp4ub&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_0vv5ew4&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceTask1 {
            get {
                return ResourceManager.GetString("ServiceTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_10a9s74&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1cnngi6&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SignalProcessStarter1 {
            get {
                return ResourceManager.GetString("SignalProcessStarter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_10a9s74&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;11.1.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1cnngi6&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SignalWaiter1 {
            get {
                return ResourceManager.GetString("SignalWaiter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_156souq&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.3.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_11729xv&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubProcess1 {
            get {
                return ResourceManager.GetString("SubProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1os0aoj&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.3.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_06nr0sh&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubProcess2 {
            get {
                return ResourceManager.GetString("SubProcess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0ivwmpw&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.3.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1s1327d&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubProcess3 {
            get {
                return ResourceManager.GetString("SubProcess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1gpwe8h&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;9.3.2&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1qfh5nd&quot; isExecutable=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Task1 {
            get {
                return ResourceManager.GetString("Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1gpwe8h&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;9.3.2&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_1qfh5nd&quot; isExecutable=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Task2 {
            get {
                return ResourceManager.GetString("Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Workflows&quot;: [
        ///        {
        ///            &quot;Name&quot;: &quot;name1.bpmn&quot;,
        ///            &quot;ServiceTasks&quot;: [
        ///                {
        ///                    &quot;Assembly&quot;: &quot;assembly1.dll&quot;,
        ///                    &quot;ClassName&quot;: &quot;className1&quot;,
        ///                    &quot;ServiceTaskName&quot;: &quot;serviceTaskName1&quot;
        ///                },
        ///                {
        ///                    &quot;Assembly&quot;: &quot;assembly1.dll&quot;,
        ///                    &quot;ClassName&quot;: &quot;className2&quot;,
        ///                    &quot;ServiceTaskName&quot;: &quot;serviceTaskName2&quot;
        ///                }
        ///            ]
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestExternals {
            get {
                return ResourceManager.GetString("TestExternals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_0acr3m6&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_0kpordz&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimerEvent1 {
            get {
                return ResourceManager.GetString("TimerEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1h9874g&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_0ez9rd5&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimerEvent2 {
            get {
                return ResourceManager.GetString("TimerEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bpmn:definitions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:bpmn=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; id=&quot;Definitions_1h9874g&quot; targetNamespace=&quot;http://bpmn.io/schema/bpmn&quot; exporter=&quot;bpmn-js (https://demo.bpmn.io)&quot; exporterVersion=&quot;10.2.0&quot;&gt;
        ///  &lt;bpmn:process id=&quot;Process_0ez9rd5&quot; isExecutable= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimerEvent3 {
            get {
                return ResourceManager.GetString("TimerEvent3", resourceCulture);
            }
        }
    }
}
